# Site settings
title:       Laurent @ Séminaire
email:       laurent@ghirardotti.fr
author:      Laurent Ghirardotti
description: "Du dév web au séminaire de Paris"
baseurl:     "/"
url:         "https://ghirardotti.fr"

# Google analytics
google_analytics: "UA-39108463-6"

layout:
  theme: nord # default, vintage, nord
  theme_highlighter: vs # default, more at css/highlighter (source: https://github.com/richleland/pygments-css)
  theme_switch: true # enable or disable user toggle switch between light and dark theme
  home_posts_no: 6
  home_postheader_title: 'Articles récents'
  home_postmeta_title: 'View all'
  posts_home: /blog/
  link_new_tab: true # should external links open in a new tab (true) or in the current tab (false)
  header_desc: true # set to false to disable description in the Header.


# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "symfonysingapore"

# Social icons
github_username: lologhi

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
