# Site settings
title:       Laurent @ Séminaire
email:       laurent@ghirardotti.fr
author:      Laurent Ghirardotti
description: "Du dév web au séminaire de Paris"
baseurl:     ""
url:         "https://ghirardotti.fr"

# Google analytics
google_analytics: "UA-39108463-6"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "symfonysingapore"

# Social icons
github_username: lologhi
stackoverflow_id: 2989138
twitter_username: lologh
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
